import { Queue } from './helpers/Queue'
import { Stack } from './helpers/Stack'

const queue = new Queue()
const stack = new Stack()
const queueArray = []
const stackArray = []
/* Queue */
queue.enqueue(1)
queue.enqueue(2)
queue.enqueue(3)
queue.enqueue(4)
queue.enqueue(5)
queue.enqueue(6)
queue.enqueue(7)
queue.enqueue(8)
queue.enqueue(9)
queue.enqueue(10)
queue.enqueue(11)
queue.enqueue(12)
queue.enqueue(13)
queue.enqueue(14)
queue.enqueue(15)

/* Queue Array */
queueArray.push(1)
queueArray.push(2)
queueArray.push(3)
queueArray.push(4)
queueArray.push(5)
queueArray.push(6)
queueArray.push(7)
queueArray.push(8)
queueArray.push(9)
queueArray.push(10)
queueArray.push(11)
queueArray.push(12)
queueArray.push(13)
queueArray.push(14)
queueArray.push(15)

console.log('Queue - Timer Initialized stack in array memory')
console.time()
queue.print(queue.firstPosition)
console.timeEnd()
console.log('Queue - Finished Timer Initialized stack in array memory')

console.log('\nQueueArray - Timer Initialized stack in array memory')
console.time()
queueArray.map(v => console.log(v))
console.timeEnd()
console.log('QueueArray - Finished Timer Initialized stack in array memory')

console.log('\n===============================================================================================================================================================================================\n')

/* Stack */
stack.push(1)
stack.push(2)
stack.push(3)
stack.push(4)
stack.push(5)
stack.push(6)
stack.push(7)
stack.push(8)
stack.push(9)
stack.push(10)
stack.push(11)
stack.push(12)
stack.push(13)
stack.push(14)
stack.push(15)

/* Stack Array */
stackArray.push(1)
stackArray.push(2)
stackArray.push(3)
stackArray.push(4)
stackArray.push(5)
stackArray.push(6)
stackArray.push(7)
stackArray.push(8)
stackArray.push(9)
stackArray.push(10)
stackArray.push(11)
stackArray.push(12)
stackArray.push(13)
stackArray.push(14)
stackArray.push(15)
stackArray.reverse()

console.log('Stack - Timer Initialized stack in memory')
console.time()
stack.print(stack.firstPosition)
console.timeEnd()
console.log('Stack - Finished Timer Initialized stack in memory')

console.log('\nStackArray - Timer Initialized stack in array memory')
console.time()
stackArray.map(v => console.log(v))
console.timeEnd()
console.log('StackArray - Finished Timer Initialized stack in array memory')
